### PR TITLE
Only send the window_update when Size - RemoteWindow > 0 to prevent over 2^31-1 limit.

### PR DESCRIPTION
**Pull request by colachengexo**
ref: https://github.com/ninenines/cowboy/issues/1369

### CODE REVIEW

**Comment by essen** [comment]
Would be good to have a test, not sure how long it'd take to exhaust the window before the patch is applied in a test scenario?

**Comment by colachengexo** [comment]
I wrote a test to let flow window over the limit. But I found the unit test using gun 1.2 won't have this issue because of this version didn't check the window size when receiving the window_update frame. Compare to gun 1.3 https://github.com/ninenines/gun/blob/1.3.0/src/gun_http2.erl#L246. It will cause test cannot finish. I don't know how to write a better test for that. Could you give me some suggestion?
Thanks!

**Comment by essen** [comment]
Yeah I had to downgrade Gun temporarily to release the latest patch. About the test well you should limit the loop of course. Just try to reproduce your issue, count the number of loops, and limit the number of loops to maybe double that if it doesn't take too long.

**Comment by colachengexo** [comment]
I made the limit for the loop. Thanks for your advice.

**Comment by essen** [comment]
Fixed via ninenines/cowboy#1400 and ninenines/cowlib#87. Closing, thanks!

**Pull request closed without merging**
