### PR TITLE
Add a step to cowboy_rest to support HTTP 429.

### PR DESCRIPTION
**Pull request by betawaffle**
See [rfc6585](http://tools.ietf.org/html/rfc6585#section-4) for an explaination of status code 429.

The callback for that example might look something like this:

``` erlang
-define(RATE_LIMIT_MSG,
        "I only allow 50 requests per hour "
        "to this Web site per logged in user.  "
        "Try again soon.").

rate_limited(Req, State) ->
    ReqCount = user_requests(Req, 3600),
    if
        ReqCount > 50 ->
            Body = error_html(<<"Too Many Requests">>,
                              <<?RATE_LIMIT_MSG>>),
            {ok, Req2} = cowboy:set_resp_body(Body, Req),
            {{true, 3600}, Req2, State};
        true ->
            {false, Req, State}
    end.

error_html(Title, Message) ->
    <<"<html>"
      "<head>"
      "<title>", Title/binary, "</title>"
      "</head>"
      "<body>"
      "<h1>", Title/binary, "</h1>"
      "<p>", Message/binary, "</p>"
      "</body>"
      "</html>">>.
```

Bring on the feedback!

### CODE REVIEW

**Comment by tnt-dev** [comment]
Any news on this?

**Comment by betawaffle** [comment]
@tnt-dev I have no immediate plans to work on this. It would have to come from someone else.

**Comment by essen** [comment]
This is something that I want to add in Cowboy 2 or soon after that, depending on time constraints.

**Comment by essen** [comment]
I've implemented this in my local copy. Compared to this it has been moved after is_authorized/forbidden so that we know the user can access the resource to begin with, and I've removed the empty true clause as I think sending retry-after is important. I also have added tests and updated the docs.

I'll push it later today and it'll be part of 2.6. Closing, thanks!

**Pull request closed without merging**
