### PR TITLE
Add support for HTTP 451 (RFC 7725)

### PR DESCRIPTION
**Pull request by nalundgaard**
I noticed that this code seems to be missing from cowboy.

See [rfc7725 section 3](https://tools.ietf.org/html/rfc7725#section-3).

### CODE REVIEW

**Comment by nalundgaard** [comment]
@essen Any chance you guys could glance this? It seems pretty straightforward. If there's anything I am missing, I would be happy to update.

**Comment by essen** [comment]
It's not a priority right now. The workaround is to send the binary (code + description) directly.

**Comment by nalundgaard** [comment]
@essen For us, we have an internal framework built on top of cowboy (recently migrated from being on top of mochiweb) for our own integrated AAA. That thing has an implicitly integer return status that would be a huge pain to unthread. For our part, we've pinned our application against my fork for now to resolve this. We'll just wait until this can be merged and tagged to pin back.

**Comment by essen** [comment]
Thanks. Please send a patch against Cowlib master to make it apply to future releases. There is no 1.1 release planned at the moment (this will be merged if there is one later on).

**Comment by nalundgaard** [comment]
@essen Isn't that what ninenines/cowlib#54 does?

**Comment by essen** [comment]
I should have looked. :-) Thanks!

**Comment by essen** [comment]
Closing 1.x tickets that are irrelevant for 2.0. Thanks!

**Pull request closed without merging**
