### PR TITLE
Fix cancelling undefined settings timer

### PR DESCRIPTION
**Pull request by tony612**
when settings_timeout is infinity

### CODE REVIEW

**Comment by essen** [comment]
Please add a test. You can mirror what https://github.com/ninenines/cowboy/blob/master/test/http2_SUITE.erl#L128 is doing and should only need to send the preface on top of that.

**Comment by tony612** [comment]
@essen The test passed on my computer, do you know why it failed in CI?
```
$ make ct-http2 t=clear:settings_timeout_infinity
TEST INFO: 1 test(s), 1 case(s) in 1 suite(s)

Testing erlang.cowboy.http2_SUITE.groups.settings_timeout_infinity: Starting test, 1 test cases
Testing erlang.cowboy.http2_SUITE.groups.settings_timeout_infinity: TEST COMPLETE, 1 ok, 0 failed of 1 test cases
```

**Comment by essen** [comment]
Might be unrelated, check https://builds.ninenines.eu/logs/cowboy-prs/82/ubuntu/

**Comment by tony612** [comment]
btw, I always got error when run `make`:
```
GEN    /Users/tony/repo/projects/erlang/cowboy/.erlang.mk/gopath/src/github.com/summerwind/h2spec/h2spec
fatal: destination path '/Users/tony/repo/projects/erlang/cowboy/.erlang.mk/gopath/src/github.com/summerwind/h2spec' already exists and is not an empty directory.
gmake: *** [Makefile:68: /Users/tony/repo/projects/erlang/cowboy/.erlang.mk/gopath/src/github.com/summerwind/h2spec/h2spec] Error 128
```
(So I have to comment that out in Makefile to let my test pass)

**Comment by tony612** [comment]
@essen It works! Is this PR okay to merge?

**Comment by tony612** [comment]
@essen Could you merge this PR?

**Comment by essen** [comment]
Merged locally, thanks!

Incidentally the test is wrong but that's not your fault, I'll fix the other infinity timeout tests at the same time.

**Pull request closed without merging**
