### PR TITLE
Cowboy Logo

### PR DESCRIPTION
**Pull request by dikaio**
New logo for your consideration.

### CODE REVIEW

**Comment by essen** [comment]
Thanks for the proposal. I don't think the logo matters that much so I rather put a personal touch there, instead of having a basho-look-alike Cowboy. But feel free to use it.

**Comment by dikaio** [comment]
That makes sense @essen, thanks for considering it. 

Never seen Basho btw :smiley: thank you.

**Comment by unbalancedparentheses** [comment]
@dikaio do you mind if I use it for a blog post?

**Comment by bfrog** [comment]
I like it the logo :+1:

**Comment by dikaio** [comment]
@unbalancedparentheses use away Fredirico! [Here's a zip file](https://s3.amazonaws.com/dikaio/cowboy-archive.zip) with all the different formats (eps, svg, png) just in case you didn't wan't to use svg.

Thanks @bfrog!

**Comment by adrianroe** [comment]
Was trying to not polite the cowboy list, but couldn’t find a direct email for you and you are DND on Slack, so my my Slack post below…

Just to say, I saw your logo PR for Cowboy and absolutely love it!

Would you mind if we use it as a favicon.ico on an (Erlang) project we are doing at the moment that serves content with Cowboy?

Nice work!

Adrian
_______________
Dr Adrian Roe
Director

**Comment by essen** [comment]
Reopening to give visibility if other people want to use it.

**Comment by dikaio** [comment]
Hey @adrianroe thank you! I did see that come in I failed to log into slack right but yes please use away, will be nice to see how you're able to get that to work with 16x16 :+1: 

Thanks @essen

**Comment by dikaio** [comment]
@essen I know you don't generally reach out to people for donations but maybe consider uploading to sticker mule and allowing people to throw on their laptop where proceeds could go back to the cowboy project. Just a thought!

**Comment by essen** [comment]
I'm not against it but when I have the choice between writing code and doing this I too often choose to write code. Right now my only priority should be getting Cowboy 2 into shape. Maybe when we get closer to release.

**Comment by dikaio** [comment]
Agreed, looking forward to Cowboy 2 most definitely!

**Comment by philipgiuliani** [comment]
Awesome work @dikaio. I like it. But it should definitely be smaller in the README i think ;)

**Comment by dikaio** [comment]
@philipgiuliani Agreed

**Comment by essen** [comment]
Closing for good this time. Cleaning up tickets. Thanks for the suggestion!

**Pull request closed without merging**
