### PR TITLE
Fix reply/4 spec

### PR DESCRIPTION
**Pull request by egobrain**
There is wrong -spec of reply/4 function 3rd parametr type must be same as [#http_req spec](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L140)

### CODE REVIEW

**Comment by essen** [comment]
Do you have an example code that makes Dialyzer fail?

**Comment by kpy3** [comment]
Code that fail:

process(Fun, Req, State) ->
    Req1 = cowboy_req:set_resp_body_fun(chunked, Fun, Req),
    {ok, Req2} = cowboy_req:reply(200, Req1),
    {ok, Req2, State}.

Dialyzer in Erlang R16B03-1 found this code correct, but dialyzer from Erlang 17.4 not.

**Comment by essen** [comment]
OK. Can you do a tiny change and move the | at the beginning of the second line instead of the end of the first line? Thanks.

**Comment by egobrain** [comment]
Fixed

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
