### PR TITLE
add Ranch link

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by essen** [comment]
Thanks but no thanks. I want people to go to ninenines.eu, not to Github, I'd leave Github if I could. So I do not want links to Github other than the one for reporting issues.

**Comment by ShalokShalom** [comment]
http://gitea.io/

**Comment by essen** [comment]
I'm not looking for a complete replacement. i'm only missing a good issue tracker that comes with oauth/whatever that github users can easily use.

**Comment by OvermindDL1** [comment]
> I'm not looking for a complete replacement. i'm only missing a good issue tracker that comes with oauth/whatever that github users can easily use.

A self-hosted gitlab then?

**Comment by essen** [comment]
Gitlab is a complete Github replacement.

**Comment by ShalokShalom** [comment]
https://www.zenhub.com/

**Comment by essen** [comment]
I don't want a github app if I'm looking to do without github.

**Comment by ShalokShalom** [comment]
I misunderstood you.

**Comment by essen** [comment]
I just need something self-hosted that comes with a button like "login via github". Mozilla's Bugzilla has it I think but not the generic Bugzilla so it's not doable. And everything else I tested either lacks it or is too complex/bad.

**Comment by ShalokShalom** [comment]
And what do you like to see in this issue tracker, compared to the Github issues?

**Comment by essen** [comment]
Github issues are more or less fine, functionality-wise. Functionality is not the issue.

**Comment by ShalokShalom** [comment]
So what else?

**Comment by essen** [comment]
Github.

Anyway I'm not here to debate the merits or flaws of Github. If I can find a replacement for tickets, great, if not I'm fine keeping them on Github for now.

**Pull request closed without merging**
