### PR TITLE
reply with a 400 status code when query string parsing fails

### PR DESCRIPTION
**Pull request by galdor**
See #887.

### CODE REVIEW

**Comment by galdor** [comment]
Using a stack trace to determine which status code to send seems incredibly fragile to me. Is there any plan to return errors differently ? Note that I am a complete erlang beginner, so I may be wrong.

**Comment by essen** [comment]
Hm you add three things, what are they? Which one is the one you did encounter?

Fragile yes, which is why this will need tests. But not much choice if we want to keep the "let it crash" behavior.

**Comment by galdor** [comment]
There are three possibles crashes:

- The parameter is missing.
- The parameter has an empty value.
- The parameter has an invalid value.

The problem here is having to match the stacktraces of all possible errors everywhere in a single function. "Let it crash" here means not being able to send the right status code at the right place.

The other problem is that even with a 400 status code, there is no indication of what is wrong with the request. So if you have a public API, and a client sends a wrong request, he gets a response without any error message. This is a very real problem in general.

**Comment by essen** [comment]
This function is there so we can follow the HTTP spec, not to make people's life easy. :-)

About knowing what's wrong, there's a ticket somewhere about improving the constraints to have details about all the failures in the requested input. Once we have that we can easily add an optional error_logger call alongside sending 400 to explain what went wrong.

**Pull request closed without merging**
