### PR TITLE
Added option to not use sendfile

### PR DESCRIPTION
**Pull request by grahamrhay**
How would you feel about something like this, Loic?

### CODE REVIEW

**Comment by grahamrhay** [comment]
workaround for #897

**Comment by essen** [comment]
That would be terrible for large files.

Look into Ranch, ranch_transport already has a sendfile function that emulates everything the normal sendfile does. All we need to do is call this function instead of the default sendfile when we disable it.

**Comment by grahamrhay** [comment]
ah, I did see that. good idea

**Comment by grahamrhay** [comment]
better?

**Comment by essen** [comment]
Don't make a new function, just have a case for calling sendfile and a case for checking the result. Also don't use on | off, use true | false. And don't forget to update typespecs and add a test.

**Comment by grahamrhay** [comment]
I'm having a bit of trouble getting the tests to pass, even without my changes. A whole bunch of this:

    maps:to_list failed
    Reason: badmap

Are there any known issues/pre-reqs? What version of erlang are you using?

This was on 1.0.3. I can't even get master to build:

    $ make
    make[1]: Entering directory '/vagrant/deps/cowboy/deps/cowlib'
    make[1]: Leaving directory '/vagrant/deps/cowboy/deps/cowlib'
    make[1]: Entering directory '/vagrant/deps/cowboy/deps/ranch'
    make[1]: Leaving directory '/vagrant/deps/cowboy/deps/ranch'
     GEN    clean-app
     GEN    clean-test-dir
     GEN    coverdata-clean
     ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_constraints.er    l     cowboy_handler.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_protocol.erl     cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_stream.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
    src/cowboy_protocol.erl:58: can't find include lib "cowlib/include/cow_parse.hrl"
    src/cowboy_protocol.erl:278: undefined macro 'IS_WS/1'
    src/cowboy_protocol.erl:440: undefined macro 'LOWER/4'
    src/cowboy_protocol.erl:266: function parse_hd_name/8 undefined
    src/cowboy_protocol.erl:413: function parse_host/3 undefined
    src/cowboy_protocol.erl:283: function parse_hd_name_ws/8 is unused
    src/cowboy_protocol.erl:290: function wait_hd_before_value/8 is unused
    src/cowboy_protocol.erl:303: function parse_hd_before_value/8 is unused
    src/cowboy_protocol.erl:322: function wait_hd_value/9 is unused
    src/cowboy_protocol.erl:337: function wait_hd_value_nl/9 is unused
    src/cowboy_protocol.erl:351: function parse_hd_value/9 is unused
    src/cowboy_protocol.erl:369: function clean_value_ws_end/2 is unused
    erlang.mk:4702: recipe for target 'ebin/cowboy.app' failed
    make[1]: *** [ebin/cowboy.app] Error 1
    erlang.mk:81: recipe for target 'all' failed
    make: *** [all] Error 2

Am I missing something?

**Comment by essen** [comment]
make distclean; make tests

**Comment by grahamrhay** [comment]
ah, yes!

**Comment by essen** [comment]
The option should rather be {sendfile, boolean()}, it should be documented and tests need to be added for the case where it is disabled.

**Comment by grahamrhay** [comment]
sorry, I had a bit of trouble getting the tests passing (without my change), and then got distracted. I'll try and find some time to finish this

**Comment by essen** [comment]
Some tests may fail normally. Just say which one fail and I'll tell you.

**Comment by grahamrhay** [comment]
@essen updated

**Comment by essen** [comment]
3 years later, I have added comparable functionality to the HTTP protocols via the `sendfile` option. This disables sendfile for the entire listener, including `cowboy_static`. I'll push it soon. Closing, thanks!

**Pull request closed without merging**
