### PR TITLE
Websocket compression

### PR DESCRIPTION
**Pull request by vans163**
Lets get this started..

### CODE REVIEW

**Comment by vans163** [comment]
I am not fully understanding this client_context_takeover and sliding window size.  Does it put extra bytes on the wire?  Or is it purely handled server/client side?

Also what is the difference between a -15 and 15 sliding window?  I see that a 15bit sliding window will take around 120kb extra memory, but will significantly decrease after compression size vs a 8bit.

https://www.igvita.com/2013/11/27/configuring-and-optimizing-websocket-compression/

**Comment by essen** [comment]
If I recall the thing about context is whether the context is kept for the whole connection or a new zlib context is created for each frames.

The plus/minus I don't recall off-hand, I probably left a comment in the code somewhere though.

**Comment by essen** [comment]
Do run "make ct-ws" after making changes to confirm they work by the way. It requires autobahntestsuite and python to be installed.

**Comment by vans163** [comment]
Dont see any related comment.  Let me try.

**Comment by vans163** [comment]
Also do you know a the equivalent when using rebar to  make:all([load]). on the erl shell?

**Comment by essen** [comment]
I don't use rebar.

If ct_run is not found then your Erlang installation is not correct and/or the paths are not set right.

**Comment by vans163** [comment]
Cowboy has the rebar.config though? How do you then make changes to cowboy.erl files and hotload them?

Strange I installed the official package from erlang repo.

It seems setting window size to 15 crashes with no error (c driver crash?).  -15 works fine.

**Comment by essen** [comment]
The rebar.config is there only for compatibility, it's generated from the Makefile.

I don't really do hot loading, I usually just run tests.

**Comment by vans163** [comment]
The test suite took 30 minutes to run for me, is there a way to speed it up? Completed with no errors.

**Comment by vans163** [comment]
Very interesting how the sliding window works with a msg that just says ping.

```
[No compression]
0000: 8104 7069 6e67  ..ping

[Compression -15 sliding]
0000: c106 2ac8 cc4b 0700  ..*..K..
0000: c105 2a00 6200 00 ..*.b..
0000: c104 0261 0000  ...a..
0000: c104 0261 0000  ...a..
```

**Comment by essen** [comment]
Most of the test suite is spent in compression tests. If there's really a bottleneck in zlib, then that's probably why it takes so long. :-)

**Comment by essen** [comment]
I've pushed configuration of Websocket deflate options. I will do the compression bit later. Closing since there's a ticket for it at ninenines/cowboy#1105 Thanks!

**Pull request closed without merging**
