### PR TITLE
idle_timeout increased to 1 hour instead of 60 seconds

### PR DESCRIPTION
**Pull request by amar1994**

### CODE REVIEW

**Comment by essen** [comment]
The default is fine. You can configure it in your own application.

**Comment by amar1994** [comment]
Can you please tell how to configure it with other application which is using cowboy?

**Comment by essen** [comment]
Please be more specific.

**Comment by amar1994** [comment]
You said I can configure it in my own application, instead of changing it in cowboy repo.

**Comment by essen** [comment]
Set the protocol options when you start the listener (alongside `env`). The list of options for HTTP/1.1 is there: https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_http/#_options

**Comment by amar1994** [comment]
@essen 
Hi,
Passing protocol option (idle_timeout) in **cowboy:start_clear/3** only sets value of idle_timeout in **cowboy_http.erl** module not in cowboy_websocket. And We are using 2.4.0 version of cowboy.

**Comment by essen** [comment]
If Websocket then it's in the options you can return from `init/2`. It's all documented. Not sure what version this got added, you might need to upgrade.

**Comment by amar1994** [comment]
@essen  Thanks.

**Pull request closed without merging**
