### PR TITLE
Add functions for getting and setting response headers

### PR DESCRIPTION
**Pull request by johlo**
Useful when writing middleware.

### CODE REVIEW

**Comment by essen** [comment]
Thanks, but it's missing tests. Check test/req_SUITE.erl

**Comment by johlo** [comment]
@essen amended tests to the commit.

**Comment by essen** [comment]
Tests are running! Thanks.

**Comment by johlo** [comment]
Anything else needs fixing for merge?

**Comment by essen** [comment]
I just need time to look into it.

**Comment by essen** [comment]
I notice that the docs are missing. Did you write them and forget to git add? If not, it shouldn't be difficult to write the two man pages based on the other cowboy_req functions that have them ready.

**Comment by essen** [comment]
Cheers, just in time, tomorrow is open source day.

**Comment by johlo** [comment]
Sorry, forgot to write them, amended now. 
Note that I could build the docs so they might be a bit off. The docbookx DTD isn't fetched when doing `make docs`

**Comment by essen** [comment]
Rebase against master and try `make asciidoc-manual`. It doesn't use DocBook for the man pages anymore.

**Comment by johlo** [comment]
with `asciidoc-manual` it produced the man pages (although it fails with unspecified error in later stage). 
Let me know if you want me to change the wording.

**Comment by essen** [comment]
Error seems to be in cowboy_rest, no worries.

**Comment by essen** [comment]
Can you give me a use case for getting all response headers? I can get why a `resp_header` function would be useful, but am having problems with a `resp_headers` function.

Also they can't be obtained through pattern matching, that field is undocumented.

**Comment by johlo** [comment]
It gives you a way of inspecting which response headers were set without having to know all the possible headers that could be set. Also I'd expect it since the bindings/headers exist.

**Comment by johlo** [comment]
I removed the pattern matching suggestion from the doc.

**Comment by essen** [comment]
Sure. Any chance you could add a resp_header at the same time then? It'll make more sense as a whole.

**Comment by johlo** [comment]
Amended with resp_header/{2,3}, with test cases and manual.

**Comment by essen** [comment]
Thanks. I should be able to get to it this week-end, documenting response functions now.

**Comment by essen** [comment]
Merging this now, great PR thanks.

**Comment by essen** [comment]
Merged with edits in the next two commits. Thanks!

**Pull request closed without merging**
