### PR TITLE
Fix wrong template name

### PR DESCRIPTION
**Pull request by anacrolix**

### CODE REVIEW

**Comment by essen** [comment]
It's not wrong, did you set `DEP_PLUGINS = cowboy`?

**Comment by anacrolix** [comment]
I did have it set. I think I didn't have `dep_cowboy_commit = 2.8.0 set`, after putting that in and cleaning the deps, the missing template appeared. So unless the template name is changed in master or future versions, this PR should be closed, sorry.

**Comment by essen** [comment]
It changed when it was moved from Erlang.mk to Cowboy itself when dep plugins were introduced. There's an Erlang.mk cleanup coming up that will remove any confusion about that soon.

**Comment by anacrolix** [comment]
Thanks @essen , sorry for the noise.

**Pull request closed without merging**
