### PR TITLE
Update examples/README.md

### PR DESCRIPTION
**Pull request by yurrriq**
Consistently use the imperative mood and add link to [LFE examples](https://github.com/quasiquoting/lfe-cowboy-examples).

### CODE REVIEW

**Comment by essen** [comment]
Merged, thanks!

**Comment by yurrriq** [comment]
Thanks for merging!

**Comment by yurrriq** [comment]
I've just realized "with lists directory entries" is a bit awkward.. Maybe "with directory listings" would be better.

**Comment by essen** [comment]
Feel free to fix, there and in the Makefile if applicable.

**Pull request merged**
