### PR TITLE
fix infinite loop on incomplete multipart in cowboy_req:read_part{,_body}/3

### PR DESCRIPTION
**Pull request by geogriff**
potential fix for #1162, with new tests.

### CODE REVIEW

**Comment by essen** [comment]
http_SUITE is deprecated, you should put them in req_SUITE instead. There's already a few for multipart.

**Comment by geogriff** [comment]
^^^ changed to req_SUITE (force pushed the branch, not sure if that is proper github etiquette or whatever..)

**Comment by essen** [comment]
Thanks. Yes force pushing is the way to go. I'll merge it soon, probably in 1-2 weeks.

**Comment by essen** [comment]
This is merged and updated locally. Thanks!

**Pull request closed without merging**
