### PR TITLE
Timeout fix

### PR DESCRIPTION
**Pull request by drapp**

### CODE REVIEW

**Comment by drapp** [comment]
sorry, ignore

**Comment by essen** [comment]
Should I expect a cleaned up PR later on?

**Comment by drapp** [comment]
We've got a bunch of changes related to spdy that we'd like to get back at some point, but we haven't gotten around to cleaning it up. Do these look like changes you want?

**Comment by essen** [comment]
Perhaps not all of it but I'm sure most of it can be merged nicely if it's sent gradually a small PR at a time.

**Pull request closed without merging**
