### PR TITLE
Active n

### PR DESCRIPTION
**Pull request by essen**
With this PR we go from 8% active time spent in `setopts` to 0.75%.

Related https://github.com/ninenines/cowboy/issues/1410

@petrohi please run a benchmark.

### CODE REVIEW

**Comment by Sebisnow** [comment]
Benchmarks for different cowboy versions and performance degradation analysis with link to this PR: https://stressgrid.com/blog/cowboy_performance_part_2/

**Comment by essen** [comment]
Yes we worked together on that.

**Comment by tony612** [comment]
Could the value `100` be an option?

**Comment by essen** [comment]
Yes it will be made an option before this is merged.

**Comment by essen** [comment]
I finished the work for this PR and merged as commit 1ece0e226cb727af9922291b491fea74fd01c84b

Thanks!

**Pull request closed without merging**
